version: 1
updates:

    -package-ecosystem: "maven"
     directory: "/"
     schedule:
        interval: "daily"
        time: "15:10"
        timezone: "America/Indiana/Indianapolis"
     target-branch: "Prod_Release_18.0"